// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public interface DataRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 id = 1;
  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  // required .Instrument instrument = 2;
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  boolean hasInstrument();
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  com.bbva.ticker.model.Instrument getInstrument();
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  com.bbva.ticker.model.InstrumentOrBuilder getInstrumentOrBuilder();

  // required .PriceDataSourceType priceDataSourceType = 3;
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 3;</code>
   */
  boolean hasPriceDataSourceType();
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 3;</code>
   */
  com.bbva.ticker.model.PriceDataSourceType getPriceDataSourceType();

  // required .PricingType pricingType = 4;
  /**
   * <code>required .PricingType pricingType = 4;</code>
   */
  boolean hasPricingType();
  /**
   * <code>required .PricingType pricingType = 4;</code>
   */
  com.bbva.ticker.model.PricingType getPricingType();
}
