// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public interface InstrumentOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 instrumentId = 1;
  /**
   * <code>required int32 instrumentId = 1;</code>
   */
  boolean hasInstrumentId();
  /**
   * <code>required int32 instrumentId = 1;</code>
   */
  int getInstrumentId();

  // required string name = 2;
  /**
   * <code>required string name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
