// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

/**
 * Protobuf enum {@code PriceDataSourceType}
 */
public enum PriceDataSourceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SOURCE1 = 0;</code>
   */
  SOURCE1(0, 0),
  /**
   * <code>SOURCE2 = 1;</code>
   */
  SOURCE2(1, 1),
  /**
   * <code>SOURCE3 = 2;</code>
   */
  SOURCE3(2, 2),
  ;

  /**
   * <code>SOURCE1 = 0;</code>
   */
  public static final int SOURCE1_VALUE = 0;
  /**
   * <code>SOURCE2 = 1;</code>
   */
  public static final int SOURCE2_VALUE = 1;
  /**
   * <code>SOURCE3 = 2;</code>
   */
  public static final int SOURCE3_VALUE = 2;


  public final int getNumber() { return value; }

  public static PriceDataSourceType valueOf(int value) {
    switch (value) {
      case 0: return SOURCE1;
      case 1: return SOURCE2;
      case 2: return SOURCE3;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PriceDataSourceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<PriceDataSourceType>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PriceDataSourceType>() {
          public PriceDataSourceType findValueByNumber(int number) {
            return PriceDataSourceType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bbva.ticker.model.TickDataProtos.getDescriptor().getEnumTypes().get(1);
  }

  private static final PriceDataSourceType[] VALUES = values();

  public static PriceDataSourceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private PriceDataSourceType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PriceDataSourceType)
}

