// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public interface PriceDataOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 id = 1;
  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  // required .Instrument instrument = 2;
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  boolean hasInstrument();
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  com.bbva.ticker.model.Instrument getInstrument();
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  com.bbva.ticker.model.InstrumentOrBuilder getInstrumentOrBuilder();

  // required string rateBid = 3;
  /**
   * <code>required string rateBid = 3;</code>
   */
  boolean hasRateBid();
  /**
   * <code>required string rateBid = 3;</code>
   */
  java.lang.String getRateBid();
  /**
   * <code>required string rateBid = 3;</code>
   */
  com.google.protobuf.ByteString
      getRateBidBytes();

  // required string rateOffer = 4;
  /**
   * <code>required string rateOffer = 4;</code>
   */
  boolean hasRateOffer();
  /**
   * <code>required string rateOffer = 4;</code>
   */
  java.lang.String getRateOffer();
  /**
   * <code>required string rateOffer = 4;</code>
   */
  com.google.protobuf.ByteString
      getRateOfferBytes();

  // required int64 dateTime = 5;
  /**
   * <code>required int64 dateTime = 5;</code>
   */
  boolean hasDateTime();
  /**
   * <code>required int64 dateTime = 5;</code>
   */
  long getDateTime();

  // required .PriceDataSourceType priceDataSourceType = 6;
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
   */
  boolean hasPriceDataSourceType();
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
   */
  com.bbva.ticker.model.PriceDataSourceType getPriceDataSourceType();
}
