// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

/**
 * Protobuf type {@code PriceData}
 */
public  final class PriceData extends
    com.google.protobuf.GeneratedMessage
    implements PriceDataOrBuilder {
  // Use PriceData.newBuilder() to construct.
  private PriceData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PriceData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PriceData defaultInstance;
  public static PriceData getDefaultInstance() {
    return defaultInstance;
  }

  public PriceData getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PriceData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            com.bbva.ticker.model.Instrument.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = instrument_.toBuilder();
            }
            instrument_ = input.readMessage(com.bbva.ticker.model.Instrument.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(instrument_);
              instrument_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            rateBid_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            rateOffer_ = input.readBytes();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            dateTime_ = input.readInt64();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            com.bbva.ticker.model.PriceDataSourceType value = com.bbva.ticker.model.PriceDataSourceType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              priceDataSourceType_ = value;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_PriceData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_PriceData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.ticker.model.PriceData.class, com.bbva.ticker.model.PriceData.Builder.class);
  }

  public static com.google.protobuf.Parser<PriceData> PARSER =
      new com.google.protobuf.AbstractParser<PriceData>() {
    public PriceData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PriceData(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PriceData> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required int32 id = 1;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  // required .Instrument instrument = 2;
  public static final int INSTRUMENT_FIELD_NUMBER = 2;
  private com.bbva.ticker.model.Instrument instrument_;
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  public boolean hasInstrument() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  public com.bbva.ticker.model.Instrument getInstrument() {
    return instrument_;
  }
  /**
   * <code>required .Instrument instrument = 2;</code>
   */
  public com.bbva.ticker.model.InstrumentOrBuilder getInstrumentOrBuilder() {
    return instrument_;
  }

  // required string rateBid = 3;
  public static final int RATEBID_FIELD_NUMBER = 3;
  private java.lang.Object rateBid_;
  /**
   * <code>required string rateBid = 3;</code>
   */
  public boolean hasRateBid() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string rateBid = 3;</code>
   */
  public java.lang.String getRateBid() {
    java.lang.Object ref = rateBid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        rateBid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string rateBid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRateBidBytes() {
    java.lang.Object ref = rateBid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rateBid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string rateOffer = 4;
  public static final int RATEOFFER_FIELD_NUMBER = 4;
  private java.lang.Object rateOffer_;
  /**
   * <code>required string rateOffer = 4;</code>
   */
  public boolean hasRateOffer() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required string rateOffer = 4;</code>
   */
  public java.lang.String getRateOffer() {
    java.lang.Object ref = rateOffer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        rateOffer_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string rateOffer = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRateOfferBytes() {
    java.lang.Object ref = rateOffer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rateOffer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required int64 dateTime = 5;
  public static final int DATETIME_FIELD_NUMBER = 5;
  private long dateTime_;
  /**
   * <code>required int64 dateTime = 5;</code>
   */
  public boolean hasDateTime() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required int64 dateTime = 5;</code>
   */
  public long getDateTime() {
    return dateTime_;
  }

  // required .PriceDataSourceType priceDataSourceType = 6;
  public static final int PRICEDATASOURCETYPE_FIELD_NUMBER = 6;
  private com.bbva.ticker.model.PriceDataSourceType priceDataSourceType_;
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
   */
  public boolean hasPriceDataSourceType() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
   */
  public com.bbva.ticker.model.PriceDataSourceType getPriceDataSourceType() {
    return priceDataSourceType_;
  }

  private void initFields() {
    id_ = 0;
    instrument_ = com.bbva.ticker.model.Instrument.getDefaultInstance();
    rateBid_ = "";
    rateOffer_ = "";
    dateTime_ = 0L;
    priceDataSourceType_ = com.bbva.ticker.model.PriceDataSourceType.SOURCE1;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasInstrument()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRateBid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasRateOffer()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDateTime()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasPriceDataSourceType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getInstrument().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, instrument_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getRateBidBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getRateOfferBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(5, dateTime_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeEnum(6, priceDataSourceType_.getNumber());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, instrument_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getRateBidBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getRateOfferBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, dateTime_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, priceDataSourceType_.getNumber());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.ticker.model.PriceData)) {
      return super.equals(obj);
    }
    com.bbva.ticker.model.PriceData other = (com.bbva.ticker.model.PriceData) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && (getId()
          == other.getId());
    }
    result = result && (hasInstrument() == other.hasInstrument());
    if (hasInstrument()) {
      result = result && getInstrument()
          .equals(other.getInstrument());
    }
    result = result && (hasRateBid() == other.hasRateBid());
    if (hasRateBid()) {
      result = result && getRateBid()
          .equals(other.getRateBid());
    }
    result = result && (hasRateOffer() == other.hasRateOffer());
    if (hasRateOffer()) {
      result = result && getRateOffer()
          .equals(other.getRateOffer());
    }
    result = result && (hasDateTime() == other.hasDateTime());
    if (hasDateTime()) {
      result = result && (getDateTime()
          == other.getDateTime());
    }
    result = result && (hasPriceDataSourceType() == other.hasPriceDataSourceType());
    if (hasPriceDataSourceType()) {
      result = result &&
          (getPriceDataSourceType() == other.getPriceDataSourceType());
    }
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
    }
    if (hasInstrument()) {
      hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getInstrument().hashCode();
    }
    if (hasRateBid()) {
      hash = (37 * hash) + RATEBID_FIELD_NUMBER;
      hash = (53 * hash) + getRateBid().hashCode();
    }
    if (hasRateOffer()) {
      hash = (37 * hash) + RATEOFFER_FIELD_NUMBER;
      hash = (53 * hash) + getRateOffer().hashCode();
    }
    if (hasDateTime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + hashLong(getDateTime());
    }
    if (hasPriceDataSourceType()) {
      hash = (37 * hash) + PRICEDATASOURCETYPE_FIELD_NUMBER;
      hash = (53 * hash) + hashEnum(getPriceDataSourceType());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.ticker.model.PriceData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.PriceData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bbva.ticker.model.PriceData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.PriceData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bbva.ticker.model.PriceData prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PriceData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.bbva.ticker.model.PriceDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_PriceData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_PriceData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.ticker.model.PriceData.class, com.bbva.ticker.model.PriceData.Builder.class);
    }

    // Construct using com.bbva.ticker.model.PriceData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getInstrumentFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (instrumentBuilder_ == null) {
        instrument_ = com.bbva.ticker.model.Instrument.getDefaultInstance();
      } else {
        instrumentBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      rateBid_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      rateOffer_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      dateTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      priceDataSourceType_ = com.bbva.ticker.model.PriceDataSourceType.SOURCE1;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_PriceData_descriptor;
    }

    public com.bbva.ticker.model.PriceData getDefaultInstanceForType() {
      return com.bbva.ticker.model.PriceData.getDefaultInstance();
    }

    public com.bbva.ticker.model.PriceData build() {
      com.bbva.ticker.model.PriceData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bbva.ticker.model.PriceData buildPartial() {
      com.bbva.ticker.model.PriceData result = new com.bbva.ticker.model.PriceData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (instrumentBuilder_ == null) {
        result.instrument_ = instrument_;
      } else {
        result.instrument_ = instrumentBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.rateBid_ = rateBid_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.rateOffer_ = rateOffer_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.dateTime_ = dateTime_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.priceDataSourceType_ = priceDataSourceType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.ticker.model.PriceData) {
        return mergeFrom((com.bbva.ticker.model.PriceData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.ticker.model.PriceData other) {
      if (other == com.bbva.ticker.model.PriceData.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasInstrument()) {
        mergeInstrument(other.getInstrument());
      }
      if (other.hasRateBid()) {
        bitField0_ |= 0x00000004;
        rateBid_ = other.rateBid_;
        onChanged();
      }
      if (other.hasRateOffer()) {
        bitField0_ |= 0x00000008;
        rateOffer_ = other.rateOffer_;
        onChanged();
      }
      if (other.hasDateTime()) {
        setDateTime(other.getDateTime());
      }
      if (other.hasPriceDataSourceType()) {
        setPriceDataSourceType(other.getPriceDataSourceType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        
        return false;
      }
      if (!hasInstrument()) {
        
        return false;
      }
      if (!hasRateBid()) {
        
        return false;
      }
      if (!hasRateOffer()) {
        
        return false;
      }
      if (!hasDateTime()) {
        
        return false;
      }
      if (!hasPriceDataSourceType()) {
        
        return false;
      }
      if (!getInstrument().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.ticker.model.PriceData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.ticker.model.PriceData) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required int32 id = 1;
    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    // required .Instrument instrument = 2;
    private com.bbva.ticker.model.Instrument instrument_ = com.bbva.ticker.model.Instrument.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.Instrument, com.bbva.ticker.model.Instrument.Builder, com.bbva.ticker.model.InstrumentOrBuilder> instrumentBuilder_;
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public boolean hasInstrument() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public com.bbva.ticker.model.Instrument getInstrument() {
      if (instrumentBuilder_ == null) {
        return instrument_;
      } else {
        return instrumentBuilder_.getMessage();
      }
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public Builder setInstrument(com.bbva.ticker.model.Instrument value) {
      if (instrumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        instrument_ = value;
        onChanged();
      } else {
        instrumentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public Builder setInstrument(
        com.bbva.ticker.model.Instrument.Builder builderForValue) {
      if (instrumentBuilder_ == null) {
        instrument_ = builderForValue.build();
        onChanged();
      } else {
        instrumentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public Builder mergeInstrument(com.bbva.ticker.model.Instrument value) {
      if (instrumentBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            instrument_ != com.bbva.ticker.model.Instrument.getDefaultInstance()) {
          instrument_ =
            com.bbva.ticker.model.Instrument.newBuilder(instrument_).mergeFrom(value).buildPartial();
        } else {
          instrument_ = value;
        }
        onChanged();
      } else {
        instrumentBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public Builder clearInstrument() {
      if (instrumentBuilder_ == null) {
        instrument_ = com.bbva.ticker.model.Instrument.getDefaultInstance();
        onChanged();
      } else {
        instrumentBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public com.bbva.ticker.model.Instrument.Builder getInstrumentBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInstrumentFieldBuilder().getBuilder();
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    public com.bbva.ticker.model.InstrumentOrBuilder getInstrumentOrBuilder() {
      if (instrumentBuilder_ != null) {
        return instrumentBuilder_.getMessageOrBuilder();
      } else {
        return instrument_;
      }
    }
    /**
     * <code>required .Instrument instrument = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.Instrument, com.bbva.ticker.model.Instrument.Builder, com.bbva.ticker.model.InstrumentOrBuilder> 
        getInstrumentFieldBuilder() {
      if (instrumentBuilder_ == null) {
        instrumentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bbva.ticker.model.Instrument, com.bbva.ticker.model.Instrument.Builder, com.bbva.ticker.model.InstrumentOrBuilder>(
                instrument_,
                getParentForChildren(),
                isClean());
        instrument_ = null;
      }
      return instrumentBuilder_;
    }

    // required string rateBid = 3;
    private java.lang.Object rateBid_ = "";
    /**
     * <code>required string rateBid = 3;</code>
     */
    public boolean hasRateBid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string rateBid = 3;</code>
     */
    public java.lang.String getRateBid() {
      java.lang.Object ref = rateBid_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        rateBid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string rateBid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRateBidBytes() {
      java.lang.Object ref = rateBid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rateBid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string rateBid = 3;</code>
     */
    public Builder setRateBid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      rateBid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string rateBid = 3;</code>
     */
    public Builder clearRateBid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rateBid_ = getDefaultInstance().getRateBid();
      onChanged();
      return this;
    }
    /**
     * <code>required string rateBid = 3;</code>
     */
    public Builder setRateBidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      rateBid_ = value;
      onChanged();
      return this;
    }

    // required string rateOffer = 4;
    private java.lang.Object rateOffer_ = "";
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public boolean hasRateOffer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public java.lang.String getRateOffer() {
      java.lang.Object ref = rateOffer_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        rateOffer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRateOfferBytes() {
      java.lang.Object ref = rateOffer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rateOffer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public Builder setRateOffer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      rateOffer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public Builder clearRateOffer() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rateOffer_ = getDefaultInstance().getRateOffer();
      onChanged();
      return this;
    }
    /**
     * <code>required string rateOffer = 4;</code>
     */
    public Builder setRateOfferBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      rateOffer_ = value;
      onChanged();
      return this;
    }

    // required int64 dateTime = 5;
    private long dateTime_ ;
    /**
     * <code>required int64 dateTime = 5;</code>
     */
    public boolean hasDateTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 dateTime = 5;</code>
     */
    public long getDateTime() {
      return dateTime_;
    }
    /**
     * <code>required int64 dateTime = 5;</code>
     */
    public Builder setDateTime(long value) {
      bitField0_ |= 0x00000010;
      dateTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 dateTime = 5;</code>
     */
    public Builder clearDateTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      dateTime_ = 0L;
      onChanged();
      return this;
    }

    // required .PriceDataSourceType priceDataSourceType = 6;
    private com.bbva.ticker.model.PriceDataSourceType priceDataSourceType_ = com.bbva.ticker.model.PriceDataSourceType.SOURCE1;
    /**
     * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
     */
    public boolean hasPriceDataSourceType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
     */
    public com.bbva.ticker.model.PriceDataSourceType getPriceDataSourceType() {
      return priceDataSourceType_;
    }
    /**
     * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
     */
    public Builder setPriceDataSourceType(com.bbva.ticker.model.PriceDataSourceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      priceDataSourceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .PriceDataSourceType priceDataSourceType = 6;</code>
     */
    public Builder clearPriceDataSourceType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      priceDataSourceType_ = com.bbva.ticker.model.PriceDataSourceType.SOURCE1;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PriceData)
  }

  static {
    defaultInstance = new PriceData(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:PriceData)
}

