// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

/**
 * Protobuf enum {@code PricingType}
 */
public enum PricingType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TICK = 0;</code>
   */
  TICK(0, 0),
  /**
   * <code>MINUTE = 1;</code>
   */
  MINUTE(1, 1),
  /**
   * <code>DAILY = 2;</code>
   */
  DAILY(2, 2),
  ;

  /**
   * <code>TICK = 0;</code>
   */
  public static final int TICK_VALUE = 0;
  /**
   * <code>MINUTE = 1;</code>
   */
  public static final int MINUTE_VALUE = 1;
  /**
   * <code>DAILY = 2;</code>
   */
  public static final int DAILY_VALUE = 2;


  public final int getNumber() { return value; }

  public static PricingType valueOf(int value) {
    switch (value) {
      case 0: return TICK;
      case 1: return MINUTE;
      case 2: return DAILY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PricingType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static com.google.protobuf.Internal.EnumLiteMap<PricingType>
      internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PricingType>() {
          public PricingType findValueByNumber(int number) {
            return PricingType.valueOf(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(index);
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bbva.ticker.model.TickDataProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final PricingType[] VALUES = values();

  public static PricingType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int index;
  private final int value;

  private PricingType(int index, int value) {
    this.index = index;
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PricingType)
}

