// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public interface RequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string identifier = 1;
  /**
   * <code>required string identifier = 1;</code>
   */
  boolean hasIdentifier();
  /**
   * <code>required string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>required string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  // required .Request.MessageType messageType = 2;
  /**
   * <code>required .Request.MessageType messageType = 2;</code>
   */
  boolean hasMessageType();
  /**
   * <code>required .Request.MessageType messageType = 2;</code>
   */
  com.bbva.ticker.model.Request.MessageType getMessageType();

  // optional .DataRequest dataRequest = 3;
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  boolean hasDataRequest();
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  com.bbva.ticker.model.DataRequest getDataRequest();
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  com.bbva.ticker.model.DataRequestOrBuilder getDataRequestOrBuilder();

  // optional .DataHistoryRequest dataHistoryRequest = 4;
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  boolean hasDataHistoryRequest();
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  com.bbva.ticker.model.DataHistoryRequest getDataHistoryRequest();
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  com.bbva.ticker.model.DataHistoryRequestOrBuilder getDataHistoryRequestOrBuilder();
}
