// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

/**
 * Protobuf type {@code Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessage
    implements RequestOrBuilder {
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Request defaultInstance;
  public static Request getDefaultInstance() {
    return defaultInstance;
  }

  public Request getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            identifier_ = input.readBytes();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            com.bbva.ticker.model.Request.MessageType value = com.bbva.ticker.model.Request.MessageType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              messageType_ = value;
            }
            break;
          }
          case 26: {
            com.bbva.ticker.model.DataRequest.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
              subBuilder = dataRequest_.toBuilder();
            }
            dataRequest_ = input.readMessage(com.bbva.ticker.model.DataRequest.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataRequest_);
              dataRequest_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            com.bbva.ticker.model.DataHistoryRequest.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
              subBuilder = dataHistoryRequest_.toBuilder();
            }
            dataHistoryRequest_ = input.readMessage(com.bbva.ticker.model.DataHistoryRequest.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dataHistoryRequest_);
              dataHistoryRequest_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_Request_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.ticker.model.Request.class, com.bbva.ticker.model.Request.Builder.class);
  }

  public static com.google.protobuf.Parser<Request> PARSER =
      new com.google.protobuf.AbstractParser<Request>() {
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code Request.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>subscribePriceData = 0;</code>
     */
    subscribePriceData(0, 0),
    /**
     * <code>unsubscribePriceData = 1;</code>
     */
    unsubscribePriceData(1, 1),
    /**
     * <code>priceDataHistory = 2;</code>
     */
    priceDataHistory(2, 2),
    ;

    /**
     * <code>subscribePriceData = 0;</code>
     */
    public static final int subscribePriceData_VALUE = 0;
    /**
     * <code>unsubscribePriceData = 1;</code>
     */
    public static final int unsubscribePriceData_VALUE = 1;
    /**
     * <code>priceDataHistory = 2;</code>
     */
    public static final int priceDataHistory_VALUE = 2;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return subscribePriceData;
        case 1: return unsubscribePriceData;
        case 2: return priceDataHistory;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bbva.ticker.model.Request.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Request.MessageType)
  }

  private int bitField0_;
  // required string identifier = 1;
  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private java.lang.Object identifier_;
  /**
   * <code>required string identifier = 1;</code>
   */
  public boolean hasIdentifier() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string identifier = 1;</code>
   */
  public java.lang.String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        identifier_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string identifier = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required .Request.MessageType messageType = 2;
  public static final int MESSAGETYPE_FIELD_NUMBER = 2;
  private com.bbva.ticker.model.Request.MessageType messageType_;
  /**
   * <code>required .Request.MessageType messageType = 2;</code>
   */
  public boolean hasMessageType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .Request.MessageType messageType = 2;</code>
   */
  public com.bbva.ticker.model.Request.MessageType getMessageType() {
    return messageType_;
  }

  // optional .DataRequest dataRequest = 3;
  public static final int DATAREQUEST_FIELD_NUMBER = 3;
  private com.bbva.ticker.model.DataRequest dataRequest_;
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  public boolean hasDataRequest() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  public com.bbva.ticker.model.DataRequest getDataRequest() {
    return dataRequest_;
  }
  /**
   * <code>optional .DataRequest dataRequest = 3;</code>
   */
  public com.bbva.ticker.model.DataRequestOrBuilder getDataRequestOrBuilder() {
    return dataRequest_;
  }

  // optional .DataHistoryRequest dataHistoryRequest = 4;
  public static final int DATAHISTORYREQUEST_FIELD_NUMBER = 4;
  private com.bbva.ticker.model.DataHistoryRequest dataHistoryRequest_;
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  public boolean hasDataHistoryRequest() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  public com.bbva.ticker.model.DataHistoryRequest getDataHistoryRequest() {
    return dataHistoryRequest_;
  }
  /**
   * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
   */
  public com.bbva.ticker.model.DataHistoryRequestOrBuilder getDataHistoryRequestOrBuilder() {
    return dataHistoryRequest_;
  }

  private void initFields() {
    identifier_ = "";
    messageType_ = com.bbva.ticker.model.Request.MessageType.subscribePriceData;
    dataRequest_ = com.bbva.ticker.model.DataRequest.getDefaultInstance();
    dataHistoryRequest_ = com.bbva.ticker.model.DataHistoryRequest.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasIdentifier()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMessageType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasDataRequest()) {
      if (!getDataRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasDataHistoryRequest()) {
      if (!getDataHistoryRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, messageType_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, dataRequest_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, dataHistoryRequest_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, messageType_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, dataRequest_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, dataHistoryRequest_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.ticker.model.Request)) {
      return super.equals(obj);
    }
    com.bbva.ticker.model.Request other = (com.bbva.ticker.model.Request) obj;

    boolean result = true;
    result = result && (hasIdentifier() == other.hasIdentifier());
    if (hasIdentifier()) {
      result = result && getIdentifier()
          .equals(other.getIdentifier());
    }
    result = result && (hasMessageType() == other.hasMessageType());
    if (hasMessageType()) {
      result = result &&
          (getMessageType() == other.getMessageType());
    }
    result = result && (hasDataRequest() == other.hasDataRequest());
    if (hasDataRequest()) {
      result = result && getDataRequest()
          .equals(other.getDataRequest());
    }
    result = result && (hasDataHistoryRequest() == other.hasDataHistoryRequest());
    if (hasDataHistoryRequest()) {
      result = result && getDataHistoryRequest()
          .equals(other.getDataHistoryRequest());
    }
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    if (hasMessageType()) {
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + hashEnum(getMessageType());
    }
    if (hasDataRequest()) {
      hash = (37 * hash) + DATAREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getDataRequest().hashCode();
    }
    if (hasDataHistoryRequest()) {
      hash = (37 * hash) + DATAHISTORYREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getDataHistoryRequest().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.ticker.model.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bbva.ticker.model.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bbva.ticker.model.Request prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.bbva.ticker.model.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.ticker.model.Request.class, com.bbva.ticker.model.Request.Builder.class);
    }

    // Construct using com.bbva.ticker.model.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getDataRequestFieldBuilder();
        getDataHistoryRequestFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      identifier_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      messageType_ = com.bbva.ticker.model.Request.MessageType.subscribePriceData;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (dataRequestBuilder_ == null) {
        dataRequest_ = com.bbva.ticker.model.DataRequest.getDefaultInstance();
      } else {
        dataRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (dataHistoryRequestBuilder_ == null) {
        dataHistoryRequest_ = com.bbva.ticker.model.DataHistoryRequest.getDefaultInstance();
      } else {
        dataHistoryRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Request_descriptor;
    }

    public com.bbva.ticker.model.Request getDefaultInstanceForType() {
      return com.bbva.ticker.model.Request.getDefaultInstance();
    }

    public com.bbva.ticker.model.Request build() {
      com.bbva.ticker.model.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bbva.ticker.model.Request buildPartial() {
      com.bbva.ticker.model.Request result = new com.bbva.ticker.model.Request(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.identifier_ = identifier_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.messageType_ = messageType_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      if (dataRequestBuilder_ == null) {
        result.dataRequest_ = dataRequest_;
      } else {
        result.dataRequest_ = dataRequestBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      if (dataHistoryRequestBuilder_ == null) {
        result.dataHistoryRequest_ = dataHistoryRequest_;
      } else {
        result.dataHistoryRequest_ = dataHistoryRequestBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.ticker.model.Request) {
        return mergeFrom((com.bbva.ticker.model.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.ticker.model.Request other) {
      if (other == com.bbva.ticker.model.Request.getDefaultInstance()) return this;
      if (other.hasIdentifier()) {
        bitField0_ |= 0x00000001;
        identifier_ = other.identifier_;
        onChanged();
      }
      if (other.hasMessageType()) {
        setMessageType(other.getMessageType());
      }
      if (other.hasDataRequest()) {
        mergeDataRequest(other.getDataRequest());
      }
      if (other.hasDataHistoryRequest()) {
        mergeDataHistoryRequest(other.getDataHistoryRequest());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasIdentifier()) {
        
        return false;
      }
      if (!hasMessageType()) {
        
        return false;
      }
      if (hasDataRequest()) {
        if (!getDataRequest().isInitialized()) {
          
          return false;
        }
      }
      if (hasDataHistoryRequest()) {
        if (!getDataHistoryRequest().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.ticker.model.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.ticker.model.Request) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string identifier = 1;
    private java.lang.Object identifier_ = "";
    /**
     * <code>required string identifier = 1;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        identifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder setIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder clearIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000001);
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      identifier_ = value;
      onChanged();
      return this;
    }

    // required .Request.MessageType messageType = 2;
    private com.bbva.ticker.model.Request.MessageType messageType_ = com.bbva.ticker.model.Request.MessageType.subscribePriceData;
    /**
     * <code>required .Request.MessageType messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Request.MessageType messageType = 2;</code>
     */
    public com.bbva.ticker.model.Request.MessageType getMessageType() {
      return messageType_;
    }
    /**
     * <code>required .Request.MessageType messageType = 2;</code>
     */
    public Builder setMessageType(com.bbva.ticker.model.Request.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .Request.MessageType messageType = 2;</code>
     */
    public Builder clearMessageType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      messageType_ = com.bbva.ticker.model.Request.MessageType.subscribePriceData;
      onChanged();
      return this;
    }

    // optional .DataRequest dataRequest = 3;
    private com.bbva.ticker.model.DataRequest dataRequest_ = com.bbva.ticker.model.DataRequest.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.DataRequest, com.bbva.ticker.model.DataRequest.Builder, com.bbva.ticker.model.DataRequestOrBuilder> dataRequestBuilder_;
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public boolean hasDataRequest() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public com.bbva.ticker.model.DataRequest getDataRequest() {
      if (dataRequestBuilder_ == null) {
        return dataRequest_;
      } else {
        return dataRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public Builder setDataRequest(com.bbva.ticker.model.DataRequest value) {
      if (dataRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataRequest_ = value;
        onChanged();
      } else {
        dataRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public Builder setDataRequest(
        com.bbva.ticker.model.DataRequest.Builder builderForValue) {
      if (dataRequestBuilder_ == null) {
        dataRequest_ = builderForValue.build();
        onChanged();
      } else {
        dataRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public Builder mergeDataRequest(com.bbva.ticker.model.DataRequest value) {
      if (dataRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            dataRequest_ != com.bbva.ticker.model.DataRequest.getDefaultInstance()) {
          dataRequest_ =
            com.bbva.ticker.model.DataRequest.newBuilder(dataRequest_).mergeFrom(value).buildPartial();
        } else {
          dataRequest_ = value;
        }
        onChanged();
      } else {
        dataRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public Builder clearDataRequest() {
      if (dataRequestBuilder_ == null) {
        dataRequest_ = com.bbva.ticker.model.DataRequest.getDefaultInstance();
        onChanged();
      } else {
        dataRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public com.bbva.ticker.model.DataRequest.Builder getDataRequestBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getDataRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    public com.bbva.ticker.model.DataRequestOrBuilder getDataRequestOrBuilder() {
      if (dataRequestBuilder_ != null) {
        return dataRequestBuilder_.getMessageOrBuilder();
      } else {
        return dataRequest_;
      }
    }
    /**
     * <code>optional .DataRequest dataRequest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.DataRequest, com.bbva.ticker.model.DataRequest.Builder, com.bbva.ticker.model.DataRequestOrBuilder> 
        getDataRequestFieldBuilder() {
      if (dataRequestBuilder_ == null) {
        dataRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bbva.ticker.model.DataRequest, com.bbva.ticker.model.DataRequest.Builder, com.bbva.ticker.model.DataRequestOrBuilder>(
                dataRequest_,
                getParentForChildren(),
                isClean());
        dataRequest_ = null;
      }
      return dataRequestBuilder_;
    }

    // optional .DataHistoryRequest dataHistoryRequest = 4;
    private com.bbva.ticker.model.DataHistoryRequest dataHistoryRequest_ = com.bbva.ticker.model.DataHistoryRequest.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.DataHistoryRequest, com.bbva.ticker.model.DataHistoryRequest.Builder, com.bbva.ticker.model.DataHistoryRequestOrBuilder> dataHistoryRequestBuilder_;
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public boolean hasDataHistoryRequest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public com.bbva.ticker.model.DataHistoryRequest getDataHistoryRequest() {
      if (dataHistoryRequestBuilder_ == null) {
        return dataHistoryRequest_;
      } else {
        return dataHistoryRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public Builder setDataHistoryRequest(com.bbva.ticker.model.DataHistoryRequest value) {
      if (dataHistoryRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataHistoryRequest_ = value;
        onChanged();
      } else {
        dataHistoryRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public Builder setDataHistoryRequest(
        com.bbva.ticker.model.DataHistoryRequest.Builder builderForValue) {
      if (dataHistoryRequestBuilder_ == null) {
        dataHistoryRequest_ = builderForValue.build();
        onChanged();
      } else {
        dataHistoryRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public Builder mergeDataHistoryRequest(com.bbva.ticker.model.DataHistoryRequest value) {
      if (dataHistoryRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008) &&
            dataHistoryRequest_ != com.bbva.ticker.model.DataHistoryRequest.getDefaultInstance()) {
          dataHistoryRequest_ =
            com.bbva.ticker.model.DataHistoryRequest.newBuilder(dataHistoryRequest_).mergeFrom(value).buildPartial();
        } else {
          dataHistoryRequest_ = value;
        }
        onChanged();
      } else {
        dataHistoryRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public Builder clearDataHistoryRequest() {
      if (dataHistoryRequestBuilder_ == null) {
        dataHistoryRequest_ = com.bbva.ticker.model.DataHistoryRequest.getDefaultInstance();
        onChanged();
      } else {
        dataHistoryRequestBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public com.bbva.ticker.model.DataHistoryRequest.Builder getDataHistoryRequestBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDataHistoryRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    public com.bbva.ticker.model.DataHistoryRequestOrBuilder getDataHistoryRequestOrBuilder() {
      if (dataHistoryRequestBuilder_ != null) {
        return dataHistoryRequestBuilder_.getMessageOrBuilder();
      } else {
        return dataHistoryRequest_;
      }
    }
    /**
     * <code>optional .DataHistoryRequest dataHistoryRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.DataHistoryRequest, com.bbva.ticker.model.DataHistoryRequest.Builder, com.bbva.ticker.model.DataHistoryRequestOrBuilder> 
        getDataHistoryRequestFieldBuilder() {
      if (dataHistoryRequestBuilder_ == null) {
        dataHistoryRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bbva.ticker.model.DataHistoryRequest, com.bbva.ticker.model.DataHistoryRequest.Builder, com.bbva.ticker.model.DataHistoryRequestOrBuilder>(
                dataHistoryRequest_,
                getParentForChildren(),
                isClean());
        dataHistoryRequest_ = null;
      }
      return dataHistoryRequestBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Request)
  }

  static {
    defaultInstance = new Request(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Request)
}

