// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

/**
 * Protobuf type {@code Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessage
    implements ResponseOrBuilder {
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Response defaultInstance;
  public static Response getDefaultInstance() {
    return defaultInstance;
  }

  public Response getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            identifier_ = input.readBytes();
            break;
          }
          case 18: {
            com.bbva.ticker.model.PriceData.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = priceData_.toBuilder();
            }
            priceData_ = input.readMessage(com.bbva.ticker.model.PriceData.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(priceData_);
              priceData_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            exception_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            message_ = input.readBytes();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              priceDataHistory_ = new java.util.ArrayList<com.bbva.ticker.model.PriceData>();
              mutable_bitField0_ |= 0x00000010;
            }
            priceDataHistory_.add(input.readMessage(com.bbva.ticker.model.PriceData.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        priceDataHistory_ = java.util.Collections.unmodifiableList(priceDataHistory_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_Response_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bbva.ticker.model.TickDataProtos.internal_static_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bbva.ticker.model.Response.class, com.bbva.ticker.model.Response.Builder.class);
  }

  public static com.google.protobuf.Parser<Response> PARSER =
      new com.google.protobuf.AbstractParser<Response>() {
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string identifier = 1;
  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private java.lang.Object identifier_;
  /**
   * <code>required string identifier = 1;</code>
   */
  public boolean hasIdentifier() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string identifier = 1;</code>
   */
  public java.lang.String getIdentifier() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        identifier_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string identifier = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdentifierBytes() {
    java.lang.Object ref = identifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional .PriceData priceData = 2;
  public static final int PRICEDATA_FIELD_NUMBER = 2;
  private com.bbva.ticker.model.PriceData priceData_;
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  public boolean hasPriceData() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  public com.bbva.ticker.model.PriceData getPriceData() {
    return priceData_;
  }
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  public com.bbva.ticker.model.PriceDataOrBuilder getPriceDataOrBuilder() {
    return priceData_;
  }

  // optional string exception = 3;
  public static final int EXCEPTION_FIELD_NUMBER = 3;
  private java.lang.Object exception_;
  /**
   * <code>optional string exception = 3;</code>
   */
  public boolean hasException() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string exception = 3;</code>
   */
  public java.lang.String getException() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        exception_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string exception = 3;</code>
   */
  public com.google.protobuf.ByteString
      getExceptionBytes() {
    java.lang.Object ref = exception_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exception_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string message = 4;
  public static final int MESSAGE_FIELD_NUMBER = 4;
  private java.lang.Object message_;
  /**
   * <code>optional string message = 4;</code>
   */
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string message = 4;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated .PriceData priceDataHistory = 5;
  public static final int PRICEDATAHISTORY_FIELD_NUMBER = 5;
  private java.util.List<com.bbva.ticker.model.PriceData> priceDataHistory_;
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  public java.util.List<com.bbva.ticker.model.PriceData> getPriceDataHistoryList() {
    return priceDataHistory_;
  }
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  public java.util.List<? extends com.bbva.ticker.model.PriceDataOrBuilder> 
      getPriceDataHistoryOrBuilderList() {
    return priceDataHistory_;
  }
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  public int getPriceDataHistoryCount() {
    return priceDataHistory_.size();
  }
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  public com.bbva.ticker.model.PriceData getPriceDataHistory(int index) {
    return priceDataHistory_.get(index);
  }
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  public com.bbva.ticker.model.PriceDataOrBuilder getPriceDataHistoryOrBuilder(
      int index) {
    return priceDataHistory_.get(index);
  }

  private void initFields() {
    identifier_ = "";
    priceData_ = com.bbva.ticker.model.PriceData.getDefaultInstance();
    exception_ = "";
    message_ = "";
    priceDataHistory_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasIdentifier()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasPriceData()) {
      if (!getPriceData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getPriceDataHistoryCount(); i++) {
      if (!getPriceDataHistory(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, priceData_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getExceptionBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getMessageBytes());
    }
    for (int i = 0; i < priceDataHistory_.size(); i++) {
      output.writeMessage(5, priceDataHistory_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getIdentifierBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, priceData_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getExceptionBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getMessageBytes());
    }
    for (int i = 0; i < priceDataHistory_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, priceDataHistory_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bbva.ticker.model.Response)) {
      return super.equals(obj);
    }
    com.bbva.ticker.model.Response other = (com.bbva.ticker.model.Response) obj;

    boolean result = true;
    result = result && (hasIdentifier() == other.hasIdentifier());
    if (hasIdentifier()) {
      result = result && getIdentifier()
          .equals(other.getIdentifier());
    }
    result = result && (hasPriceData() == other.hasPriceData());
    if (hasPriceData()) {
      result = result && getPriceData()
          .equals(other.getPriceData());
    }
    result = result && (hasException() == other.hasException());
    if (hasException()) {
      result = result && getException()
          .equals(other.getException());
    }
    result = result && (hasMessage() == other.hasMessage());
    if (hasMessage()) {
      result = result && getMessage()
          .equals(other.getMessage());
    }
    result = result && getPriceDataHistoryList()
        .equals(other.getPriceDataHistoryList());
    result = result &&
        getUnknownFields().equals(other.getUnknownFields());
    return result;
  }

  private int memoizedHashCode = 0;
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    if (hasPriceData()) {
      hash = (37 * hash) + PRICEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getPriceData().hashCode();
    }
    if (hasException()) {
      hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
      hash = (53 * hash) + getException().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (getPriceDataHistoryCount() > 0) {
      hash = (37 * hash) + PRICEDATAHISTORY_FIELD_NUMBER;
      hash = (53 * hash) + getPriceDataHistoryList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bbva.ticker.model.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bbva.ticker.model.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bbva.ticker.model.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.bbva.ticker.model.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.bbva.ticker.model.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.bbva.ticker.model.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.bbva.ticker.model.Response prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.bbva.ticker.model.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbva.ticker.model.Response.class, com.bbva.ticker.model.Response.Builder.class);
    }

    // Construct using com.bbva.ticker.model.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getPriceDataFieldBuilder();
        getPriceDataHistoryFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      identifier_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (priceDataBuilder_ == null) {
        priceData_ = com.bbva.ticker.model.PriceData.getDefaultInstance();
      } else {
        priceDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      exception_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (priceDataHistoryBuilder_ == null) {
        priceDataHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        priceDataHistoryBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bbva.ticker.model.TickDataProtos.internal_static_Response_descriptor;
    }

    public com.bbva.ticker.model.Response getDefaultInstanceForType() {
      return com.bbva.ticker.model.Response.getDefaultInstance();
    }

    public com.bbva.ticker.model.Response build() {
      com.bbva.ticker.model.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.bbva.ticker.model.Response buildPartial() {
      com.bbva.ticker.model.Response result = new com.bbva.ticker.model.Response(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.identifier_ = identifier_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (priceDataBuilder_ == null) {
        result.priceData_ = priceData_;
      } else {
        result.priceData_ = priceDataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.exception_ = exception_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.message_ = message_;
      if (priceDataHistoryBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          priceDataHistory_ = java.util.Collections.unmodifiableList(priceDataHistory_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.priceDataHistory_ = priceDataHistory_;
      } else {
        result.priceDataHistory_ = priceDataHistoryBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bbva.ticker.model.Response) {
        return mergeFrom((com.bbva.ticker.model.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bbva.ticker.model.Response other) {
      if (other == com.bbva.ticker.model.Response.getDefaultInstance()) return this;
      if (other.hasIdentifier()) {
        bitField0_ |= 0x00000001;
        identifier_ = other.identifier_;
        onChanged();
      }
      if (other.hasPriceData()) {
        mergePriceData(other.getPriceData());
      }
      if (other.hasException()) {
        bitField0_ |= 0x00000004;
        exception_ = other.exception_;
        onChanged();
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000008;
        message_ = other.message_;
        onChanged();
      }
      if (priceDataHistoryBuilder_ == null) {
        if (!other.priceDataHistory_.isEmpty()) {
          if (priceDataHistory_.isEmpty()) {
            priceDataHistory_ = other.priceDataHistory_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePriceDataHistoryIsMutable();
            priceDataHistory_.addAll(other.priceDataHistory_);
          }
          onChanged();
        }
      } else {
        if (!other.priceDataHistory_.isEmpty()) {
          if (priceDataHistoryBuilder_.isEmpty()) {
            priceDataHistoryBuilder_.dispose();
            priceDataHistoryBuilder_ = null;
            priceDataHistory_ = other.priceDataHistory_;
            bitField0_ = (bitField0_ & ~0x00000010);
            priceDataHistoryBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPriceDataHistoryFieldBuilder() : null;
          } else {
            priceDataHistoryBuilder_.addAllMessages(other.priceDataHistory_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasIdentifier()) {
        
        return false;
      }
      if (hasPriceData()) {
        if (!getPriceData().isInitialized()) {
          
          return false;
        }
      }
      for (int i = 0; i < getPriceDataHistoryCount(); i++) {
        if (!getPriceDataHistory(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bbva.ticker.model.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bbva.ticker.model.Response) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string identifier = 1;
    private java.lang.Object identifier_ = "";
    /**
     * <code>required string identifier = 1;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        identifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder setIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      identifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder clearIdentifier() {
      bitField0_ = (bitField0_ & ~0x00000001);
      identifier_ = getDefaultInstance().getIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>required string identifier = 1;</code>
     */
    public Builder setIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      identifier_ = value;
      onChanged();
      return this;
    }

    // optional .PriceData priceData = 2;
    private com.bbva.ticker.model.PriceData priceData_ = com.bbva.ticker.model.PriceData.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder> priceDataBuilder_;
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public boolean hasPriceData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public com.bbva.ticker.model.PriceData getPriceData() {
      if (priceDataBuilder_ == null) {
        return priceData_;
      } else {
        return priceDataBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public Builder setPriceData(com.bbva.ticker.model.PriceData value) {
      if (priceDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        priceData_ = value;
        onChanged();
      } else {
        priceDataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public Builder setPriceData(
        com.bbva.ticker.model.PriceData.Builder builderForValue) {
      if (priceDataBuilder_ == null) {
        priceData_ = builderForValue.build();
        onChanged();
      } else {
        priceDataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public Builder mergePriceData(com.bbva.ticker.model.PriceData value) {
      if (priceDataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            priceData_ != com.bbva.ticker.model.PriceData.getDefaultInstance()) {
          priceData_ =
            com.bbva.ticker.model.PriceData.newBuilder(priceData_).mergeFrom(value).buildPartial();
        } else {
          priceData_ = value;
        }
        onChanged();
      } else {
        priceDataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public Builder clearPriceData() {
      if (priceDataBuilder_ == null) {
        priceData_ = com.bbva.ticker.model.PriceData.getDefaultInstance();
        onChanged();
      } else {
        priceDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public com.bbva.ticker.model.PriceData.Builder getPriceDataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPriceDataFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    public com.bbva.ticker.model.PriceDataOrBuilder getPriceDataOrBuilder() {
      if (priceDataBuilder_ != null) {
        return priceDataBuilder_.getMessageOrBuilder();
      } else {
        return priceData_;
      }
    }
    /**
     * <code>optional .PriceData priceData = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder> 
        getPriceDataFieldBuilder() {
      if (priceDataBuilder_ == null) {
        priceDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder>(
                priceData_,
                getParentForChildren(),
                isClean());
        priceData_ = null;
      }
      return priceDataBuilder_;
    }

    // optional string exception = 3;
    private java.lang.Object exception_ = "";
    /**
     * <code>optional string exception = 3;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string exception = 3;</code>
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        exception_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string exception = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string exception = 3;</code>
     */
    public Builder setException(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      exception_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string exception = 3;</code>
     */
    public Builder clearException() {
      bitField0_ = (bitField0_ & ~0x00000004);
      exception_ = getDefaultInstance().getException();
      onChanged();
      return this;
    }
    /**
     * <code>optional string exception = 3;</code>
     */
    public Builder setExceptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      exception_ = value;
      onChanged();
      return this;
    }

    // optional string message = 4;
    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 4;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000008);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 4;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      message_ = value;
      onChanged();
      return this;
    }

    // repeated .PriceData priceDataHistory = 5;
    private java.util.List<com.bbva.ticker.model.PriceData> priceDataHistory_ =
      java.util.Collections.emptyList();
    private void ensurePriceDataHistoryIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        priceDataHistory_ = new java.util.ArrayList<com.bbva.ticker.model.PriceData>(priceDataHistory_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder> priceDataHistoryBuilder_;

    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public java.util.List<com.bbva.ticker.model.PriceData> getPriceDataHistoryList() {
      if (priceDataHistoryBuilder_ == null) {
        return java.util.Collections.unmodifiableList(priceDataHistory_);
      } else {
        return priceDataHistoryBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public int getPriceDataHistoryCount() {
      if (priceDataHistoryBuilder_ == null) {
        return priceDataHistory_.size();
      } else {
        return priceDataHistoryBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public com.bbva.ticker.model.PriceData getPriceDataHistory(int index) {
      if (priceDataHistoryBuilder_ == null) {
        return priceDataHistory_.get(index);
      } else {
        return priceDataHistoryBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder setPriceDataHistory(
        int index, com.bbva.ticker.model.PriceData value) {
      if (priceDataHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.set(index, value);
        onChanged();
      } else {
        priceDataHistoryBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder setPriceDataHistory(
        int index, com.bbva.ticker.model.PriceData.Builder builderForValue) {
      if (priceDataHistoryBuilder_ == null) {
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.set(index, builderForValue.build());
        onChanged();
      } else {
        priceDataHistoryBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder addPriceDataHistory(com.bbva.ticker.model.PriceData value) {
      if (priceDataHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.add(value);
        onChanged();
      } else {
        priceDataHistoryBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder addPriceDataHistory(
        int index, com.bbva.ticker.model.PriceData value) {
      if (priceDataHistoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.add(index, value);
        onChanged();
      } else {
        priceDataHistoryBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder addPriceDataHistory(
        com.bbva.ticker.model.PriceData.Builder builderForValue) {
      if (priceDataHistoryBuilder_ == null) {
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.add(builderForValue.build());
        onChanged();
      } else {
        priceDataHistoryBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder addPriceDataHistory(
        int index, com.bbva.ticker.model.PriceData.Builder builderForValue) {
      if (priceDataHistoryBuilder_ == null) {
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.add(index, builderForValue.build());
        onChanged();
      } else {
        priceDataHistoryBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder addAllPriceDataHistory(
        java.lang.Iterable<? extends com.bbva.ticker.model.PriceData> values) {
      if (priceDataHistoryBuilder_ == null) {
        ensurePriceDataHistoryIsMutable();
        super.addAll(values, priceDataHistory_);
        onChanged();
      } else {
        priceDataHistoryBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder clearPriceDataHistory() {
      if (priceDataHistoryBuilder_ == null) {
        priceDataHistory_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        priceDataHistoryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public Builder removePriceDataHistory(int index) {
      if (priceDataHistoryBuilder_ == null) {
        ensurePriceDataHistoryIsMutable();
        priceDataHistory_.remove(index);
        onChanged();
      } else {
        priceDataHistoryBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public com.bbva.ticker.model.PriceData.Builder getPriceDataHistoryBuilder(
        int index) {
      return getPriceDataHistoryFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public com.bbva.ticker.model.PriceDataOrBuilder getPriceDataHistoryOrBuilder(
        int index) {
      if (priceDataHistoryBuilder_ == null) {
        return priceDataHistory_.get(index);  } else {
        return priceDataHistoryBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public java.util.List<? extends com.bbva.ticker.model.PriceDataOrBuilder> 
         getPriceDataHistoryOrBuilderList() {
      if (priceDataHistoryBuilder_ != null) {
        return priceDataHistoryBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(priceDataHistory_);
      }
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public com.bbva.ticker.model.PriceData.Builder addPriceDataHistoryBuilder() {
      return getPriceDataHistoryFieldBuilder().addBuilder(
          com.bbva.ticker.model.PriceData.getDefaultInstance());
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public com.bbva.ticker.model.PriceData.Builder addPriceDataHistoryBuilder(
        int index) {
      return getPriceDataHistoryFieldBuilder().addBuilder(
          index, com.bbva.ticker.model.PriceData.getDefaultInstance());
    }
    /**
     * <code>repeated .PriceData priceDataHistory = 5;</code>
     */
    public java.util.List<com.bbva.ticker.model.PriceData.Builder> 
         getPriceDataHistoryBuilderList() {
      return getPriceDataHistoryFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder> 
        getPriceDataHistoryFieldBuilder() {
      if (priceDataHistoryBuilder_ == null) {
        priceDataHistoryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bbva.ticker.model.PriceData, com.bbva.ticker.model.PriceData.Builder, com.bbva.ticker.model.PriceDataOrBuilder>(
                priceDataHistory_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        priceDataHistory_ = null;
      }
      return priceDataHistoryBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Response)
  }

  static {
    defaultInstance = new Response(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Response)
}

