// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public interface ResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string identifier = 1;
  /**
   * <code>required string identifier = 1;</code>
   */
  boolean hasIdentifier();
  /**
   * <code>required string identifier = 1;</code>
   */
  java.lang.String getIdentifier();
  /**
   * <code>required string identifier = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdentifierBytes();

  // optional .PriceData priceData = 2;
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  boolean hasPriceData();
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  com.bbva.ticker.model.PriceData getPriceData();
  /**
   * <code>optional .PriceData priceData = 2;</code>
   */
  com.bbva.ticker.model.PriceDataOrBuilder getPriceDataOrBuilder();

  // optional string exception = 3;
  /**
   * <code>optional string exception = 3;</code>
   */
  boolean hasException();
  /**
   * <code>optional string exception = 3;</code>
   */
  java.lang.String getException();
  /**
   * <code>optional string exception = 3;</code>
   */
  com.google.protobuf.ByteString
      getExceptionBytes();

  // optional string message = 4;
  /**
   * <code>optional string message = 4;</code>
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  // repeated .PriceData priceDataHistory = 5;
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  java.util.List<com.bbva.ticker.model.PriceData> 
      getPriceDataHistoryList();
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  com.bbva.ticker.model.PriceData getPriceDataHistory(int index);
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  int getPriceDataHistoryCount();
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  java.util.List<? extends com.bbva.ticker.model.PriceDataOrBuilder> 
      getPriceDataHistoryOrBuilderList();
  /**
   * <code>repeated .PriceData priceDataHistory = 5;</code>
   */
  com.bbva.ticker.model.PriceDataOrBuilder getPriceDataHistoryOrBuilder(
      int index);
}
