// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pricing.proto

package com.bbva.ticker.model;

public final class TickDataProtos {
  private TickDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Instrument_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Instrument_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_DataHistoryRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataHistoryRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_DataRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DataRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_PriceData_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PriceData_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpricing.proto\"0\n\nInstrument\022\024\n\014instrum" +
      "entId\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\"\246\001\n\022DataHistor" +
      "yRequest\022\n\n\002id\030\001 \002(\005\022\037\n\ninstrument\030\002 \002(\013" +
      "2\013.Instrument\0221\n\023priceDataSourceType\030\003 \002" +
      "(\0162\024.PriceDataSourceType\022!\n\013pricingType\030" +
      "\004 \002(\0162\014.PricingType\022\r\n\005count\030\005 \002(\005\"\220\001\n\013D" +
      "ataRequest\022\n\n\002id\030\001 \002(\005\022\037\n\ninstrument\030\002 \002" +
      "(\0132\013.Instrument\0221\n\023priceDataSourceType\030\003" +
      " \002(\0162\024.PriceDataSourceType\022!\n\013pricingTyp" +
      "e\030\004 \002(\0162\014.PricingType\"\363\001\n\007Request\022\022\n\nide",
      "ntifier\030\001 \002(\t\022)\n\013messageType\030\002 \002(\0162\024.Req" +
      "uest.MessageType\022!\n\013dataRequest\030\003 \001(\0132\014." +
      "DataRequest\022/\n\022dataHistoryRequest\030\004 \001(\0132" +
      "\023.DataHistoryRequest\"U\n\013MessageType\022\026\n\022s" +
      "ubscribePriceData\020\000\022\030\n\024unsubscribePriceD" +
      "ata\020\001\022\024\n\020priceDataHistory\020\002\"\241\001\n\tPriceDat" +
      "a\022\n\n\002id\030\001 \002(\005\022\037\n\ninstrument\030\002 \002(\0132\013.Inst" +
      "rument\022\017\n\007rateBid\030\003 \002(\t\022\021\n\trateOffer\030\004 \002" +
      "(\t\022\020\n\010dateTime\030\005 \002(\003\0221\n\023priceDataSourceT" +
      "ype\030\006 \002(\0162\024.PriceDataSourceType\"\207\001\n\010Resp",
      "onse\022\022\n\nidentifier\030\001 \002(\t\022\035\n\tpriceData\030\002 " +
      "\001(\0132\n.PriceData\022\021\n\texception\030\003 \001(\t\022\017\n\007me" +
      "ssage\030\004 \001(\t\022$\n\020priceDataHistory\030\005 \003(\0132\n." +
      "PriceData*.\n\013PricingType\022\010\n\004TICK\020\000\022\n\n\006MI" +
      "NUTE\020\001\022\t\n\005DAILY\020\002*<\n\023PriceDataSourceType" +
      "\022\013\n\007SOURCE1\020\000\022\013\n\007SOURCE2\020\001\022\013\n\007SOURCE3\020\002B" +
      ",\n\025com.bbva.ticker.modelB\016TickDataProtos" +
      "P\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Instrument_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Instrument_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Instrument_descriptor,
              new java.lang.String[] { "InstrumentId", "Name", });
          internal_static_DataHistoryRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_DataHistoryRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DataHistoryRequest_descriptor,
              new java.lang.String[] { "Id", "Instrument", "PriceDataSourceType", "PricingType", "Count", });
          internal_static_DataRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_DataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DataRequest_descriptor,
              new java.lang.String[] { "Id", "Instrument", "PriceDataSourceType", "PricingType", });
          internal_static_Request_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Request_descriptor,
              new java.lang.String[] { "Identifier", "MessageType", "DataRequest", "DataHistoryRequest", });
          internal_static_PriceData_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_PriceData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PriceData_descriptor,
              new java.lang.String[] { "Id", "Instrument", "RateBid", "RateOffer", "DateTime", "PriceDataSourceType", });
          internal_static_Response_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Response_descriptor,
              new java.lang.String[] { "Identifier", "PriceData", "Exception", "Message", "PriceDataHistory", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
